-- AlterTable
ALTER TABLE "Trade" ADD COLUMN     "mae_pips" DOUBLE PRECISION,
ADD COLUMN     "mae_price" DOUBLE PRECISION,
ADD COLUMN     "mae_r" DOUBLE PRECISION,
ADD COLUMN     "mfe_pips" DOUBLE PRECISION,
ADD COLUMN     "mfe_price" DOUBLE PRECISION,
ADD COLUMN     "mfe_r" DOUBLE PRECISION;
